[2024-06-13T12:55:36.817+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-13T12:55:36.841+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xdag_id_1.query_the_table manual__2024-06-13T12:55:20.668155+00:00 [queued]>
[2024-06-13T12:55:36.850+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xdag_id_1.query_the_table manual__2024-06-13T12:55:20.668155+00:00 [queued]>
[2024-06-13T12:55:36.851+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-13T12:55:36.867+0000] {taskinstance.py:2330} INFO - Executing <Task(PostgreSQLCountRows): query_the_table> on 2024-06-13 12:55:20.668155+00:00
[2024-06-13T12:55:36.874+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=159) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-13T12:55:36.877+0000] {standard_task_runner.py:63} INFO - Started process 161 to run task
[2024-06-13T12:55:36.877+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'xdag_id_1', 'query_the_table', 'manual__2024-06-13T12:55:20.668155+00:00', '--job-id', '887', '--raw', '--subdir', 'DAGS_FOLDER/jobs_dag.py', '--cfg-path', '/tmp/tmpbmlfwl38']
[2024-06-13T12:55:36.880+0000] {standard_task_runner.py:91} INFO - Job 887: Subtask query_the_table
[2024-06-13T12:55:36.932+0000] {task_command.py:426} INFO - Running <TaskInstance: xdag_id_1.query_the_table manual__2024-06-13T12:55:20.668155+00:00 [running]> on host 55555dc522f3
[2024-06-13T12:55:37.035+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xdag_id_1' AIRFLOW_CTX_TASK_ID='query_the_table' AIRFLOW_CTX_EXECUTION_DATE='2024-06-13T12:55:20.668155+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-13T12:55:20.668155+00:00'
[2024-06-13T12:55:37.038+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-13T12:55:37.064+0000] {base.py:84} INFO - Using connection ID 'postgres_default' for task execution.
[2024-06-13T12:55:37.069+0000] {sql.py:470} INFO - Running statement: SELECT COUNT(*) FROM table_name_1;, parameters: None
[2024-06-13T12:55:37.071+0000] {sql.py:479} INFO - Rows affected: 1
[2024-06-13T12:55:37.085+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-13T12:55:37.095+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=xdag_id_1, task_id=query_the_table, run_id=manual__2024-06-13T12:55:20.668155+00:00, execution_date=20240613T125520, start_date=20240613T125536, end_date=20240613T125537
[2024-06-13T12:55:37.141+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-13T12:55:37.163+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-13T12:55:37.166+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
