[2024-06-19T09:43:06.969+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-19T09:43:07.010+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_dag_id.file_sensor manual__2024-06-19T09:42:58.853262+00:00 [queued]>
[2024-06-19T09:43:07.023+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_dag_id.file_sensor manual__2024-06-19T09:42:58.853262+00:00 [queued]>
[2024-06-19T09:43:07.026+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-19T09:43:07.047+0000] {taskinstance.py:2330} INFO - Executing <Task(CustomFileSensor): file_sensor> on 2024-06-19 09:42:58.853262+00:00
[2024-06-19T09:43:07.058+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=69) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-19T09:43:07.119+0000] {standard_task_runner.py:63} INFO - Started process 71 to run task
[2024-06-19T09:43:07.130+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'trigger_dag_id', 'file_sensor', 'manual__2024-06-19T09:42:58.853262+00:00', '--job-id', '936', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/tmp/tmp8nrcj8_t']
[2024-06-19T09:43:07.160+0000] {standard_task_runner.py:91} INFO - Job 936: Subtask file_sensor
[2024-06-19T09:43:07.305+0000] {task_command.py:426} INFO - Running <TaskInstance: trigger_dag_id.file_sensor manual__2024-06-19T09:42:58.853262+00:00 [running]> on host 3c9100f9b2f4
[2024-06-19T09:43:07.440+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='trigger_dag_id' AIRFLOW_CTX_TASK_ID='file_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-06-19T09:42:58.853262+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-19T09:42:58.853262+00:00'
[2024-06-19T09:43:07.443+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-19T09:43:07.444+0000] {baseoperator.py:399} WARNING - CustomFileSensor.execute cannot be called outside TaskInstance!
[2024-06-19T09:43:07.467+0000] {base.py:84} INFO - Using connection ID 'fs_default' for task execution.
[2024-06-19T09:43:07.469+0000] {filesystem.py:85} INFO - Poking for file /opt/***/TRIGGER_FILE/file.txt
[2024-06-19T09:43:07.472+0000] {filesystem.py:89} INFO - Found File /opt/***/TRIGGER_FILE/file.txt last modified: 20240411090055
[2024-06-19T09:43:07.472+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-06-19T09:43:07.473+0000] {filesystem.py:85} INFO - Poking for file /opt/***/TRIGGER_FILE/file.txt
[2024-06-19T09:43:07.474+0000] {filesystem.py:89} INFO - Found File /opt/***/TRIGGER_FILE/file.txt last modified: 20240411090055
[2024-06-19T09:43:07.475+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-19T09:43:07.490+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=trigger_dag_id, task_id=file_sensor, run_id=manual__2024-06-19T09:42:58.853262+00:00, execution_date=20240619T094258, start_date=20240619T094307, end_date=20240619T094307
[2024-06-19T09:43:07.525+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-19T09:43:07.571+0000] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-06-19T09:43:07.574+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
