[2024-06-05T11:37:15.950+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T11:37:15.990+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: xdag_id_1.check_if_table_exists manual__2024-06-05T11:37:05.293314+00:00 [queued]>
[2024-06-05T11:37:16.001+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: xdag_id_1.check_if_table_exists manual__2024-06-05T11:37:05.293314+00:00 [queued]>
[2024-06-05T11:37:16.002+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-05T11:37:16.024+0000] {taskinstance.py:2330} INFO - Executing <Task(_BranchPythonDecoratedOperator): check_if_table_exists> on 2024-06-05 11:37:05.293314+00:00
[2024-06-05T11:37:16.034+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3349) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-05T11:37:16.037+0000] {standard_task_runner.py:63} INFO - Started process 3351 to run task
[2024-06-05T11:37:16.037+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'xdag_id_1', 'check_if_table_exists', 'manual__2024-06-05T11:37:05.293314+00:00', '--job-id', '420', '--raw', '--subdir', 'DAGS_FOLDER/jobs_dag.py', '--cfg-path', '/tmp/tmp58y_9d3g']
[2024-06-05T11:37:16.042+0000] {standard_task_runner.py:91} INFO - Job 420: Subtask check_if_table_exists
[2024-06-05T11:37:16.109+0000] {task_command.py:426} INFO - Running <TaskInstance: xdag_id_1.check_if_table_exists manual__2024-06-05T11:37:05.293314+00:00 [running]> on host db8c7b709f57
[2024-06-05T11:37:16.251+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='xdag_id_1' AIRFLOW_CTX_TASK_ID='check_if_table_exists' AIRFLOW_CTX_EXECUTION_DATE='2024-06-05T11:37:05.293314+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-05T11:37:05.293314+00:00'
[2024-06-05T11:37:16.253+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T11:37:16.254+0000] {python.py:237} INFO - Done. Returned value was: insert_new_row
[2024-06-05T11:37:16.256+0000] {branch.py:36} INFO - Branch into insert_new_row
[2024-06-05T11:37:16.257+0000] {skipmixin.py:178} INFO - Following branch insert_new_row
[2024-06-05T11:37:16.283+0000] {skipmixin.py:246} INFO - Skipping tasks [('create_table', -1)]
[2024-06-05T11:37:16.319+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T11:37:16.343+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=xdag_id_1, task_id=check_if_table_exists, run_id=manual__2024-06-05T11:37:05.293314+00:00, execution_date=20240605T113705, start_date=20240605T113715, end_date=20240605T113716
[2024-06-05T11:37:16.383+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-05T11:37:16.426+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-05T11:37:16.429+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
