[2024-06-05T11:37:04.456+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-06-05T11:37:04.480+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: trigger_dag_id.file_sensor manual__2024-06-05T11:37:01.825344+00:00 [queued]>
[2024-06-05T11:37:04.491+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: trigger_dag_id.file_sensor manual__2024-06-05T11:37:01.825344+00:00 [queued]>
[2024-06-05T11:37:04.492+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 1
[2024-06-05T11:37:04.512+0000] {taskinstance.py:2330} INFO - Executing <Task(FileSensor): file_sensor> on 2024-06-05 11:37:01.825344+00:00
[2024-06-05T11:37:04.519+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=3326) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2024-06-05T11:37:04.521+0000] {standard_task_runner.py:63} INFO - Started process 3328 to run task
[2024-06-05T11:37:04.521+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'trigger_dag_id', 'file_sensor', 'manual__2024-06-05T11:37:01.825344+00:00', '--job-id', '415', '--raw', '--subdir', 'DAGS_FOLDER/trigger_dag.py', '--cfg-path', '/tmp/tmpwdvu6inv']
[2024-06-05T11:37:04.524+0000] {standard_task_runner.py:91} INFO - Job 415: Subtask file_sensor
[2024-06-05T11:37:04.597+0000] {task_command.py:426} INFO - Running <TaskInstance: trigger_dag_id.file_sensor manual__2024-06-05T11:37:01.825344+00:00 [running]> on host db8c7b709f57
[2024-06-05T11:37:04.737+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='trigger_dag_id' AIRFLOW_CTX_TASK_ID='file_sensor' AIRFLOW_CTX_EXECUTION_DATE='2024-06-05T11:37:01.825344+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-06-05T11:37:01.825344+00:00'
[2024-06-05T11:37:04.743+0000] {taskinstance.py:430} INFO - ::endgroup::
[2024-06-05T11:37:04.745+0000] {baseoperator.py:399} WARNING - FileSensor.execute cannot be called outside TaskInstance!
[2024-06-05T11:37:04.759+0000] {base.py:84} INFO - Using connection ID 'fs_default' for task execution.
[2024-06-05T11:37:04.761+0000] {filesystem.py:85} INFO - Poking for file /opt/***/TRIGGER_FILE/file.txt
[2024-06-05T11:37:04.763+0000] {filesystem.py:89} INFO - Found File /opt/***/TRIGGER_FILE/file.txt last modified: 20240411090055
[2024-06-05T11:37:04.764+0000] {base.py:294} INFO - Success criteria met. Exiting.
[2024-06-05T11:37:04.764+0000] {filesystem.py:85} INFO - Poking for file /opt/***/TRIGGER_FILE/file.txt
[2024-06-05T11:37:04.765+0000] {filesystem.py:89} INFO - Found File /opt/***/TRIGGER_FILE/file.txt last modified: 20240411090055
[2024-06-05T11:37:04.766+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-06-05T11:37:04.777+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=trigger_dag_id, task_id=file_sensor, run_id=manual__2024-06-05T11:37:01.825344+00:00, execution_date=20240605T113701, start_date=20240605T113704, end_date=20240605T113704
[2024-06-05T11:37:04.828+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-06-05T11:37:04.867+0000] {taskinstance.py:3498} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-06-05T11:37:04.871+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
